name: Compile NebulaT

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos Environment
        uses: Randomblock1/theos-action@v1

      - name: Compile Dylib
        run: |
          make SDKVERSION=16.4 ARCHS="arm64 arm64e" TARGET=iphone:clang:latest:15.0

      - name: Upload Finished Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NebulaT-Dylib
          path: .theos/obj/debug/*.dylib
